fix bug: xjar log split

diff --git a/xjar b/xjar
--- a/xjar
+++ b/xjar
@@ -121,9 +121,8 @@ e.g.
 __xj_redirect() {
     [ -s "$2" ] && return 1;
     mkdir -p "${2%/*}" || return 1;
-    local xj_user=$(ps -ef | awk '/^[^[:space:]]+[[:space:]]+'"$1"'[[:space:]]+/{printf $1}');
     touch "$2";
-    chown $xj_user:$(id -gn $xj_user) "$2";
+    chown $3 "$2"; # ps -p $1 -o user | awk '{if(NR == 2) printf $1}'
 #     gdb -p $1 >/dev/null 2>&1 <<GDB
 # set scheduler-locking on
 # print close(1)
@@ -197,6 +196,12 @@ __xj_main() {
         xj_jar_name="${xj_jar_name%.*}";
         # xj_args_file="$XJ_JAR_LOG_DIR/$xj_jar_name.args";
         xj_jar_dir="${xj_jar_path%/*}/";
+        xj_user=`ls -l "$xj_jar_dir"/*.jar 2>/dev/null | awk '{if(NR == 1) printf $3}'`;
+        [ "$xj_user" ] || {
+            printf "[\033[1;31mERROR\033[0m] '\033[32m%s\033[0m' not work directory.\n" "$xj_jar_dir" >&2;
+            exit 1
+        };
+        xj_group=$(id -gn $xj_user);
         xj_java_pid=$(ps -ef | awk '/[[:space:]]+[0-9]{2}(:[0-9]{2}){2}[[:space:]]java[[:space:]].*'"${xj_jar_dir//\//\\/}"'.*\.jar/{print $2}');
 
         [ "$XJ_LOG_PREFIX" ] && {
@@ -256,12 +261,6 @@ __xj_main() {
                 ;;
             esac
 
-            xj_user=`ls -l "$xj_jar_dir"/*.jar 2>/dev/null | awk '{if(NR == 1) print $3}'`;
-            [ "$xj_user" ] || {
-                printf "[\033[1;31mERROR\033[0m] '\033[32m%s\033[0m' not work directory.\n" "$xj_jar_dir" >&2;
-                exit 1
-            };
-            xj_group=$(id -gn $xj_user);
             mkdir -pv "$XJ_JAR_LOG_DIR";
             chown -R $xj_user:$xj_group "$XJ_JAR_LOG_DIR";
             # echo "$@" > "$xj_args_file" && chown $xj_user:$xj_group "$xj_args_file";
@@ -398,7 +397,7 @@ __xj_main() {
                 done < <(ps -ef | awk '/strftime\(/{system("readlink --canonicalize /proc/" $2 "/fd/0")}' | awk -F '/' '{print $3, $5}')
             fi
 
-            __xj_redirect $xj_pid "$xj_jar_log_file" || {
+            __xj_redirect $xj_pid "$xj_jar_log_file" $xj_user:$xj_group || {
                 printf "name:\033[1m%-26s\033[0m [\033[1;31mERROR\033[0m] target log file '$xj_jar_log_file' exist and not empty.\n" $xj_jar_name, >&2;
                 exit 1
             }
