fix var init bug

diff --git a/xjar b/xjar
--- a/xjar
+++ b/xjar
@@ -111,7 +111,9 @@ param:
 \033[1moption\033[0m:
     start   [-D|--debug [port]]     start jar if not run. (support debug)
     stop    [-f]                    stop jar process. (force stop)
-    log     [lines|-[days]]         print last n lines and n days before log.
+    log     [lines|-[days]]         print last n lines and n days before log. (default $XJ_LOG_PRINT_LAST_LINES lines)
+                                e.g.
+                                    ${0##*/} log 100 -0 # today the last 100 lines.
     restart [-D|--debug [port]]     restart jar process. (support debug)
     status                          show process info.
     live                            start jar if not run,
@@ -171,10 +173,12 @@ __xj_load_config() {
 }
 
 __xj_main() {
-    : ${XJ_LOCAL_XJAR_CONFIG_NAME:='.xjarconf'}
-
     # unset environment variables
     unset CLASSPATH JAVA_HOME $( set | awk -F = '/^(XJ|xj)_[0-9A-Za-z_]+=/{printf " " $1}');
+
+    XJ_LOCAL_XJAR_CONFIG_NAME='.xjarconf';
+    XJ_LOG_PRINT_LAST_LINES=69;
+    XJ_FIND_JAR_MAX_DEPTH=2;
 
     __xj_load_config /etc/xjar.conf;
     __xj_load_config $HOME/.xjarc;
@@ -208,12 +212,11 @@ __xj_main() {
         xj_jar_name="${xj_jar_name%.*}";
         # xj_args_file="$XJ_JAR_LOG_DIR/$xj_jar_name.args";
         xj_jar_dir="${xj_jar_path%/*}/";
-        xj_user=`ls -l "$xj_jar_dir"/*.jar 2>/dev/null | awk '{if(NR == 1) printf $3}'`;
-        [ "$xj_user" ] || {
-            printf "[\033[1;31mERROR\033[0m] '\033[32m%s\033[0m' not work directory.\n" "$xj_jar_dir" >&2;
+        xj_user=`ls -l "$xj_jar_path" | awk '{if(NR == 1) printf $3}'`;
+        xj_group=$(id -gn ${xj_user:-0,} 2>/dev/null) || {
+            printf "[\033[1;31mERROR\033[0m] the file '\033[32m%s.jar\033[0m' owner user '\033[32m%s\033[0m' does not exist.\n" "$xj_jar_name" "$xj_user" >&2;
             exit 1
-        };
-        xj_group=$(id -gn $xj_user);
+        }
         xj_java_pid=$(ps -ef | awk '/[[:space:]]+[0-9]{2}(:[0-9]{2}){2}[[:space:]]java[[:space:]].*'"${xj_jar_dir//\//\\/}"'.*\.jar/{print $2}');
 
         [ "$XJ_LOG_PREFIX" ] && {
@@ -292,7 +295,7 @@ __xj_main() {
             chown $xj_user:$xj_group "$xj_jar_log_file";
             su --shell $SHELL $xj_user --command "$0" >> "$xj_jar_log_file";
 
-            [ "$HISTCONTROL" -a ! "$TEAMCITY_VERSION" ] && {
+            [ "$TERM" != "dumb" -a ! "$TEAMCITY_VERSION" ] && {
                 if [ "$XJ_MAIN_CLASS_PATH" ]; then
                     set -- $XJ_JAVA_ARGS -cp "$xj_jar_path" $XJ_MAIN_CLASS_PATH $XJ_JAR_ARGS;
                 else
@@ -307,14 +310,14 @@ __xj_main() {
         log)
             __xj_test_workspace;
             shift;
-            [ "$1" == "${1/-[0-9]/}" ] || set -- ${2:-10} $1;
+            [ "$1" == "${1/-[0-9]/}" ] || set -- ${2:-$XJ_LOG_PRINT_LAST_LINES} $1;
             xj_jar_log_file="$(date -d "${2:-0} days" +$XJ_JAR_LOG_DIR/${xj_jar_name}_%Y%m%d.log)";
 
-            if [ "$HISTCONTROL" -a ! "$TEAMCITY_VERSION" ] && [ ! "$2" ]; then
-                set -- -F -n ${1:-10};
+            if [ "$TERM" != "dumb" -a ! "$TEAMCITY_VERSION" ] && [ ! "$2" ]; then
+                set -- -F -n ${1:-$XJ_LOG_PRINT_LAST_LINES};
 
             else
-                set -- -n ${1:-10};
+                set -- -n ${1:-$XJ_LOG_PRINT_LAST_LINES};
                 printf "\n"
 
             fi
@@ -442,9 +445,9 @@ __xj_main() {
                     bash "$0" "$@";
                 )
                 xj_act=true
-            done < <(find "${__dir__[@]}" -maxdepth ${XJ_MAX_DEPTH:-2} -type f -name $XJ_LOCAL_XJAR_CONFIG_NAME);
+            done < <(find "${__dir__[@]}" -maxdepth $XJ_FIND_JAR_MAX_DEPTH -type f -name $XJ_LOCAL_XJAR_CONFIG_NAME);
             [ "$xj_act" ] || \
-                printf "[\033[1;31mERROR\033[0m] '\033[32m%s\033[0m' no $XJ_LOCAL_XJAR_CONFIG_NAME found, find depth is ${XJ_MAX_DEPTH:-2}.\n" $1 >&2;
+                printf "[\033[1;31mERROR\033[0m] '\033[32m%s\033[0m' no $XJ_LOCAL_XJAR_CONFIG_NAME found, find depth is $XJ_FIND_JAR_MAX_DEPTH.\n" $1 >&2;
             unset __dir__ __sh__
 
         ;;
@@ -492,14 +495,15 @@ Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin
 Cmnd_Alias  JAR_RUNNER = $0
 
 # User privilege specification
-$USER       ALL=(ALL)    NOPASSWD: JAR_RUNNER
+$USER       ALL=(ALL)   NOPASSWD: JAR_RUNNER
 \033[0mEOF
 " >&2;
 
         printf "
 Globle config:
     cat > \033[32m/etc/xjar.conf\033[0m <<-EOF\033[7m
-MAX_DEPTH=2;
+FIND_JAR_MAX_DEPTH=2;
+# LOG_PRINT_LAST_LINES=69
 # LOCAL_XJAR_CONFIG_NAME=.xjarconf
 # MINUS_1_ARG=./xjar
 JAVA_ARGS=' -Xmx1024m'
