change xjar status output

diff --git a/xjar b/xjar
--- a/xjar
+++ b/xjar
@@ -367,7 +367,7 @@ __xj_main() {
             if [ "$xj_java_pid" ]; then
                 printf "name:\033[1m%-26s\033[0m pid:\033[1m%-6s\033[0m %-23s" ${PWD##*/}, $xj_java_pid, \
                 $(which netstat >/dev/null 2>&1 && netstat -lnp 2>/dev/null | awk '/[^0-9]'$xj_java_pid'\/java/{if(!e++) printf " port:"; sub(/.*:/, "", $4); sub(/[46]$/, "", $1); printf "\033[1m%s/%s\033[0m,", $4, $1}');
-                top -b -n 1 -p$xj_java_pid | tac | awk '{if($0 ~ /^KiB Mem/){printf " (\033[1m%.2f\033[0m/\033[1m%.0f\033[0mg)\n", ($8/1024/1024), ($4/1024/1024)} else if($0 ~ /java/){b[""]=1;b["m"]=1024;b["g"]=(1024*1024);s=$6;sub(/[gm]/, "", $6);sub(/[0-9\.]+/, "", s);printf " cpu:\033[1m%-6s\033[0m mem:\033[1m%-8s\033[0m", $9 "%,", sprintf("%.2f", $6*b[s]/1024/1024) "g" }}';
+                ps -p$xj_java_pid -o pcpu,pmem,rss | awk 'NR == 2 {printf " cpu:\033[1m%-6s\033[0m mem:\033[1m%-8s\033[0m\n", $1 "%", $2 "% (" sprintf("%.2f", $3/1024/1024) "g)"}'
 
             else
                 printf "name:\033[1m%-26s\033[0m inactive (\033[31mdead\033[0m).\n" ${PWD##*/}, >&2;
@@ -401,7 +401,7 @@ __xj_main() {
             __xj_test_command reredirect || exit 1;
             __xj_test_command readlink || exit 1;
             [ "$xj_java_pid" ] || {
-                printf "name:\033[1m%-26s\033[0m [\033[1;31mERROR\033[0m] not running.\n" $xj_jar_name, >&2;
+                [ "$TERM" == "dumb" ] || printf "name:\033[1m%-26s\033[0m [\033[1;31mERROR\033[0m] not running.\n" $xj_jar_name, >&2;
                 exit 1
             };
             __xj_test_workspace;
