update xjar

diff --git a/xjar b/xjar
--- a/xjar
+++ b/xjar
@@ -13,32 +13,27 @@
 #   See the License for the specific language governing permissions and
 #   limitations under the License.
 
-__xj_unset() {
-    # clear environment variables
-    unset CLASSPATH JAVA_HOME $(set | awk -F = '/^(XJ|xj)_[0-9A-Za-z_]+=/{printf " " $1}')
-}
-
-[ "$xj_jar_path" ] && {
+__xj_run () {
+    # todo XJ_JAR_ARGS support ""
     if [ "$XJ_MAIN_CLASS_PATH" ]; then
-        set -- $XJ_JAVA_ARGS -cp "$xj_jar_path" $XJ_MAIN_CLASS_PATH $XJ_JAR_ARGS;
+        set -- java $XJ_JAVA_ARGS -cp "$xj_jar_path" $XJ_MAIN_CLASS_PATH $XJ_JAR_ARGS;
     else
-        set -- $XJ_JAVA_ARGS -jar "$xj_jar_path" $XJ_JAR_ARGS;
+        set -- java $XJ_JAVA_ARGS -jar "$xj_jar_path" $XJ_JAR_ARGS;
     fi
+
+    [ -x $XJ_MINUS_1_ARG ] && set -- $XJ_MINUS_1_ARG "$@";
+
     (
-        REPLY="$xj_jar_log_prefix";
 
-        # clear sub environment variables
-        __xj_unset;
-
-        # clear functions
-        unset $(set | awk '/^__xj_[0-9A-Za-z_]+[[:space:]]*\(/{printf " " $1}');
-
-        if [ "$REPLY" ]; then
-            nohup < /dev/null java "$@" 2>&1 | awk '{print '"$REPLY"';fflush(stdout)}' &
-            unset REPLY
+        if [ "$xj_jar_log_prefix" ]; then
+            {
+                unset $(set | awk -F '[=[:space:]]' '/^(__)?(XJ|xj)_[0-9A-Za-z_]+(=|[[:space:]]\()/{printf " " $1}');
+                nohup < /dev/null "$@"
+            } 2>&1 | awk '{print '"$xj_jar_log_prefix"';fflush(stdout)}' &
 
         else
-            nohup < /dev/null java "$@" 2>&1 &
+            unset $(set | awk -F '[=[:space:]]' '/^(__)?(XJ|xj)_[0-9A-Za-z_]+(=|[[:space:]]\()/{printf " " $1}');
+            nohup < /dev/null "$@" 2>&1 &
 
         fi
 
@@ -72,6 +67,23 @@ __xj_unset() {
     )
     exit 0
 
+}
+
+__xj_test_zip_head() {
+    local xj_file_head XJ_ZIP_HEAD;
+    printf -v XJ_ZIP_HEAD PK\\x03\\x04;
+    read xj_file_head < "$1" 2>/dev/null;
+    [ "$XJ_ZIP_HEAD" == "${xj_file_head:0:4}" ] || {
+        printf "[\033[1;31mERROR\033[0m] '$1' not jar file.\n" >&2;
+        return 1
+    };
+    return 0
+}
+
+[ "$xj_jar_path" -a -s "$xj_jar_path" ] && {
+    __xj_test_zip_head "$xj_jar_path" || exit 1;
+    __xj_run;
+    exit
 }
 
 __xj_help() {
@@ -109,7 +121,9 @@ e.g.
 __xj_redirect() {
     [ -s "$2" ] && return 1;
     mkdir -p "${2%/*}" || return 1;
+    local xj_user=$(ps -ef | awk '/^[^[:space:]]+[[:space:]]+'"$1"'[[:space:]]+/{printf $1}');
     touch "$2";
+    chown $xj_user:$(id -gn $xj_user) "$2";
 #     gdb -p $1 >/dev/null 2>&1 <<GDB
 # set scheduler-locking on
 # print close(1)
@@ -119,6 +133,7 @@ __xj_redirect() {
 # quit
 # GDB
     reredirect -N -m "$2" $1
+
 }
 
 __xj_test_command() {
@@ -145,7 +160,9 @@ __xj_load_config() {
 
 : ${XJ_LOCAL_XJAR_CONFIG_NAME:='.xjarconf'}
 
-__xj_unset;
+# clear environment variables
+unset CLASSPATH JAVA_HOME $(set | awk -F = '/^(XJ|xj)_[0-9A-Za-z_]+=/{printf " " $1}');
+
 __xj_load_config /etc/xjar.conf;
 __xj_load_config $HOME/.xjarc;
 __xj_load_config $XJ_LOCAL_XJAR_CONFIG_NAME;
@@ -173,17 +190,13 @@ xj_jar_path="${xj_jar_path/'-sources.'/.}";
 xj_jar_path="${xj_jar_path/'-src.'/.}";
 
 [ -s "$xj_jar_path" ] && {
-    printf -v xj_zip_head PK\\x03\\x04;
-    read xj_jar_head < "$xj_jar_path";
-    [ "$xj_zip_head" == "${xj_jar_head:0:4}" ] || {
-        printf "[\033[1;31mERROR\033[0m] '$xj_jar_path' not jar file.\n";
-        exit 1
-    };
+    __xj_test_zip_head "$xj_jar_path" || exit 1;
     xj_jar_name="${xj_jar_path##*/}";
     xj_jar_name="${xj_jar_name%.*}";
     # xj_args_file="$XJ_JAR_LOG_DIR/$xj_jar_name.args";
     xj_jar_dir="${xj_jar_path%/*}/";
     xj_java_pid=$(ps -ef | awk '/[[:space:]]+[0-9]{2}(:[0-9]{2}){2}[[:space:]]java[[:space:]].*'"${xj_jar_dir//\//\\/}"'.*\.jar/{print $2}');
+
     [ "$XJ_LOG_PREFIX" ] && {
         # man date
         [ "$XJ_LOG_PREFIX" == "${XJ_LOG_PREFIX/\%[A-DF-IMNPR-Za-eghj-npr-z]/}" -a "$XJ_LOG_PREFIX" == "${XJ_LOG_PREFIX/\%-[A-DF-IMNPR-Za-eghj-npr-z]/}" ] && {
@@ -241,17 +254,25 @@ case $1 in
             ;;
         esac
 
-        mkdir -pv $XJ_JAR_LOG_DIR;
-        # echo "$@" > "$xj_args_file";
-        xj_jar_log_file="$(date +$XJ_JAR_LOG_DIR/${xj_jar_name}_%Y%m%d.log)";
-
         xj_user=`ls -l "$xj_jar_dir"/*.jar 2>/dev/null | awk '{if(NR == 1) print $3}'`;
         [ "$xj_user" ] || {
             printf "[\033[1;31mERROR\033[0m] '\033[32m%s\033[0m' not work directory.\n" "$xj_jar_dir" >&2;
             exit 1
-        }
+        };
+        xj_group=$(id -gn $xj_user);
+        mkdir -pv "$XJ_JAR_LOG_DIR";
+        chown -R $xj_user:$xj_group "$XJ_JAR_LOG_DIR";
+        # echo "$@" > "$xj_args_file" && chown $xj_user:$xj_group "$xj_args_file";
+        xj_jar_log_file="$(date +$XJ_JAR_LOG_DIR/${xj_jar_name}_%Y%m%d.log)";
 
-        export xj_jar_path xj_jar_log_prefix XJ_JAVA_ARGS XJ_JAR_ARGS XJ_MAIN_CLASS_PATH;
+        if [ -s $XJ_MINUS_1_ARG ]; then
+            [ -x $XJ_MINUS_1_ARG ] || {
+                printf "[\033[1;31mERROR\033[0m] '\033[32m%s\033[0m' not have executable permissions.\n" "$XJ_MINUS_1_ARG" >&2;
+                exit 1
+            };
+        fi
+
+        export xj_jar_path xj_jar_log_prefix XJ_JAVA_ARGS XJ_JAR_ARGS XJ_MAIN_CLASS_PATH XJ_MINUS_1_ARG;
 
         su --shell $SHELL $xj_user --command "$0" >> "$xj_jar_log_file";
 
@@ -362,6 +383,7 @@ case $1 in
         };
         __xj_test_workspace;
         __xj_test_single_process;
+        # test awk prefix
         xj_jar_log_file="$(date +$XJ_JAR_LOG_DIR/${xj_jar_name}_%Y%m%d.log)";
         xj_java_fd="$(readlink --canonicalize /proc/$xj_java_pid/fd/1)";
         xj_pid=$xj_java_pid;
@@ -373,6 +395,7 @@ case $1 in
                 };
             done < <(ps -ef | awk '/strftime\(/{system("readlink --canonicalize /proc/" $2 "/fd/0")}' | awk -F '/' '{print $3, $5}')
         fi
+
         __xj_redirect $xj_pid "$xj_jar_log_file" || {
             printf "name:\033[1m%-26s\033[0m [\033[1;31mERROR\033[0m] target log file '$xj_jar_log_file' exist and not empty.\n" $xj_jar_name, >&2;
             exit 1
@@ -389,7 +412,7 @@ case $1 in
         __args__=$(awk -F \) '/^[[:space:]]*[A-Za-z|-]+)/{gsub(/\|/, " ", $1); printf " %s ", $1}' "$0");
         # make sure path exist and not match case
         while [ -d "$1" -a "${__args__/ $1 /}" == "$__args__" ]; do __dir__[${#__dir__[@]}]="$1"; shift; done
-        unset __args__ xj_run;
+        unset __args__ xj_act;
         export TEAMCITY_VERSION=none HISTCONTROL=;
         while read __sh__; do
             (
@@ -397,9 +420,9 @@ case $1 in
                 unset __dir__ __sh__;
                 bash "$0" "$@";
             )
-            xj_run=true
+            xj_act=true
         done < <(find "${__dir__[@]}" -maxdepth ${XJ_MAX_DEPTH:-2} -type f -name $XJ_LOCAL_XJAR_CONFIG_NAME);
-        [ "$xj_run" ] || \
+        [ "$xj_act" ] || \
             printf "[\033[1;31mERROR\033[0m] '\033[32m%s\033[0m' no $XJ_LOCAL_XJAR_CONFIG_NAME found, find depth is ${XJ_MAX_DEPTH:-2}.\n" $1 >&2;
         unset __dir__ __sh__
 
@@ -413,6 +436,7 @@ case $1 in
             printf "[\033[1;31mERROR\033[0m] '\033[32m%s\033[0m' server directory must exist.\n" $1 >&2;
             exit 1
         };
+        # todo /etc/cron.d/
         xj_cron_expression="0 0 * * * $SHELL $0 -d ${1%/} redirect";
         xj_cron_text=$(crontab -l 2>/dev/null);
         if [ "$xj_cron_text" ]; then
@@ -443,6 +467,7 @@ Globle config:
     cat > \033[32m/etc/xjar.conf\033[0m <<-EOF\033[7m
 MAX_DEPTH=2;
 # LOCAL_XJAR_CONFIG_NAME=.xjarconf
+# MINUS_1_ARG=./xjar
 JAVA_ARGS=' -Xmx1024m'
 JAVA_ARGS+=' -Xms1024m'
 \033[0mEOF
